import { useState, useEffect, useMemo, useRef } from 'react';
import { useNavigate, useParams } from 'react-router';
import { trpc } from '@/providers/trpc';
import { unitTypes, appConfig } from '@/config';
import { ArrowLeft, Plus, Trash2, FileText, DollarSign, Percent, ClipboardList } from 'lucide-react';
import { buildSuggestedLineItems, calculateProjectTotals, formatCurrency, toNumber } from '@/utils/estimate';

const lineItemScopes = Array.from(new Set([
  'Paint - Walls', 'Paint - Ceiling', 'Paint - Trim', 'Paint - Doors',
  'Drywall Repair', 'Texture Work', 'Priming', 'Caulking',
  'Prep Work', 'Masking', 'Cleanup', 'Material',
]));

export default function EstimateBuilder() {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();
  const utils = trpc.useUtils();
  const pid = Number(projectId);

  const { data: project } = trpc.projects.get.useQuery({ id: pid });
  const { data: rooms = [] } = trpc.rooms.list.useQuery({ projectId: pid });
  const { data: lineItems = [] } = trpc.lineItems.list.useQuery({ projectId: pid });

  const createItem = trpc.lineItems.create.useMutation({
    onSuccess: () => utils.lineItems.list.invalidate({ projectId: pid }),
  });
  const deleteItem = trpc.lineItems.delete.useMutation({
    onSuccess: () => utils.lineItems.list.invalidate({ projectId: pid }),
  });
  const recalcProject = trpc.lineItems.recalcProject.useMutation({
    onSuccess: () => utils.projects.get.invalidate({ id: pid }),
  });
  const updateProject = trpc.projects.update.useMutation({
    onSuccess: () => utils.projects.get.invalidate({ id: pid }),
  });

  const [showAddForm, setShowAddForm] = useState(false);
  const [newItem, setNewItem] = useState({
    description: '', scope: '', quantity: '1', unit: 'ea', rate: '', roomId: 0,
  });
  const [taxRate, setTaxRate] = useState(Number(project?.taxRate) || 0);
  const [discount, setDiscount] = useState(Number(project?.discountAmount) || 0);
  const hasAutogeneratedRef = useRef(false);

  const { customerItems, subtotal, taxAmount, total, depositAmount } = useMemo(
    () => calculateProjectTotals(lineItems, taxRate, discount),
    [lineItems, taxRate, discount]
  );

  useEffect(() => {
    if (!project) return;
    setTaxRate(Number(project.taxRate) || 0);
    setDiscount(Number(project.discountAmount) || 0);
  }, [project?.id, project?.taxRate, project?.discountAmount]);

  // Auto-generate line items from the saved room data if none exist yet.
  useEffect(() => {
    if (rooms.length === 0 || lineItems.length > 0 || hasAutogeneratedRef.current) return;

    hasAutogeneratedRef.current = true;

    void (async () => {
      for (const room of rooms) {
        const suggestions = buildSuggestedLineItems(room);
        for (const suggestion of suggestions) {
          await createItem.mutateAsync({
            projectId: pid,
            roomId: room.id,
            description: suggestion.description,
            category: suggestion.category,
            scope: suggestion.scope,
            quantity: suggestion.quantity,
            unit: suggestion.unit,
            rate: suggestion.rate,
            subtotal: suggestion.subtotal,
            sortOrder: suggestion.sortOrder,
          });
        }
      }

      recalcProject.mutate({ projectId: pid });
    })();
  }, [createItem, lineItems.length, pid, recalcProject, rooms]);

  const handleAddItem = () => {
    if (!newItem.description.trim() || !newItem.rate) return;
    const qty = Number(newItem.quantity) || 1;
    const rate = Number(newItem.rate) || 0;
    createItem.mutate({
      projectId: pid,
      roomId: newItem.roomId || undefined,
      description: newItem.description,
      scope: newItem.scope || undefined,
      quantity: qty,
      unit: newItem.unit,
      rate,
      subtotal: qty * rate,
    }, {
          onSuccess: () => {
        setNewItem({ description: '', scope: '', quantity: '1', unit: 'ea', rate: '', roomId: 0 });
        setShowAddForm(false);
        recalcProject.mutate({ projectId: pid });
      },
    });
  };

  const handleDelete = (id: number) => {
    deleteItem.mutate({ id }, { onSuccess: () => recalcProject.mutate({ projectId: pid }) });
  };

  const handleUpdatePricing = () => {
    updateProject.mutate({
      id: pid,
      subtotal,
      taxRate,
      taxAmount,
      discountAmount: discount,
      total,
      depositAmount,
    });
  };

  const groupedByRoom = useMemo(() => {
    const map = new Map<number | null, typeof lineItems>();
    customerItems.forEach((item) => {
      const key = item.roomId;
      if (!map.has(key)) map.set(key, []);
      map.get(key)!.push(item);
    });
    return map;
  }, [customerItems]);

  return (
    <div className="min-h-screen w-full bg-black text-[#e0e0e0]">
      <header className="sticky top-0 z-30 liquid-glass">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center justify-between">
          <button onClick={() => navigate(`/project/${pid}/rooms`)} className="p-2 -ml-2 rounded-lg hover:bg-white/5 transition-colors text-[#888]">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="absolute left-1/2 -translate-x-1/2 text-center">
            <h1 className="text-sm font-semibold">Estimate Builder</h1>
            <p className="text-[10px] text-[#888]">{customerItems.length} line items</p>
          </div>
          <button
            onClick={() => setShowAddForm(!showAddForm)}
            className="p-2 rounded-lg hover:bg-white/5 transition-colors text-amber-400"
          >
            <Plus className="w-5 h-5" />
          </button>
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-4 py-4 pb-32">
        {/* Progress */}
        <div className="flex items-center gap-2 mb-6 px-1">
          {['Setup', 'Rooms', 'Estimate', 'Review'].map((step, i) => (
            <div key={step} className="flex items-center gap-2 flex-1">
              <div className={`w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-medium ${
                i === 2 ? 'bg-amber-500 text-white' : 'bg-white/[0.06] text-[#555]'
              }`}>
                {i + 1}
              </div>
              <span className={`text-[10px] ${i === 2 ? 'text-amber-400' : 'text-[#555]'}`}>{step}</span>
              {i < 3 && <div className="flex-1 h-px bg-white/[0.06]" />}
            </div>
          ))}
        </div>

        {/* Summary Card */}
        <div className="rounded-2xl bg-gradient-to-br from-amber-500/10 to-amber-600/5 border border-amber-500/20 p-4 mb-6">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <span className="text-[10px] text-[#888] uppercase tracking-wider">Subtotal</span>
              <p className="text-lg font-semibold">{formatCurrency(subtotal)}</p>
            </div>
            <div>
              <span className="text-[10px] text-[#888] uppercase tracking-wider">Total</span>
              <p className="text-2xl font-bold text-amber-400">{formatCurrency(total)}</p>
            </div>
          </div>
          <div className="mt-4 pt-4 border-t border-amber-500/15 flex items-center justify-between gap-3">
            <p className="text-xs text-[#888]">Line items are now generated from each room’s dimensions, scope, repairs, and trim details.</p>
            <button
              onClick={() => navigate(`/project/${pid}/materials`)}
              className="shrink-0 inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs text-amber-300 hover:bg-white/5 transition-colors"
            >
              <ClipboardList className="w-3.5 h-3.5" />
              Materials
            </button>
          </div>
        </div>

        {/* Add Form */}
        {showAddForm && (
          <div className="rounded-2xl bg-white/[0.03] border border-white/[0.08] p-4 mb-6">
            <h3 className="text-xs font-medium text-[#888] uppercase tracking-wider mb-3">Add Line Item</h3>
            <div className="space-y-3">
              <input
                type="text"
                value={newItem.description}
                onChange={(e) => setNewItem({ ...newItem, description: e.target.value })}
                placeholder="Description"
                className="w-full bg-white/[0.04] border border-white/[0.08] rounded-xl px-4 py-3 text-sm outline-none focus:border-amber-500/40 transition-colors placeholder:text-[#555]"
              />
              <select
                value={newItem.scope}
                onChange={(e) => setNewItem({ ...newItem, scope: e.target.value })}
                className="w-full bg-white/[0.04] border border-white/[0.08] rounded-xl px-4 py-3 text-sm outline-none focus:border-amber-500/40 transition-colors appearance-none text-[#e0e0e0]"
              >
                <option value="">Select scope</option>
                {lineItemScopes.map((s) => <option key={s} value={s}>{s}</option>)}
              </select>
              <select
                value={newItem.roomId || ''}
                onChange={(e) => setNewItem({ ...newItem, roomId: Number(e.target.value) })}
                className="w-full bg-white/[0.04] border border-white/[0.08] rounded-xl px-4 py-3 text-sm outline-none focus:border-amber-500/40 transition-colors appearance-none text-[#e0e0e0]"
              >
                <option value="">No room</option>
                {rooms.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}
              </select>
              <div className="grid grid-cols-3 gap-3">
                <input
                  type="number"
                  value={newItem.quantity}
                  onChange={(e) => setNewItem({ ...newItem, quantity: e.target.value })}
                  placeholder="Qty"
                  className="w-full bg-white/[0.04] border border-white/[0.08] rounded-xl px-4 py-3 text-sm outline-none focus:border-amber-500/40 transition-colors"
                />
                <select
                  value={newItem.unit}
                  onChange={(e) => setNewItem({ ...newItem, unit: e.target.value })}
                  className="w-full bg-white/[0.04] border border-white/[0.08] rounded-xl px-4 py-3 text-sm outline-none focus:border-amber-500/40 transition-colors appearance-none text-[#e0e0e0]"
                >
                  {unitTypes.map((u) => <option key={u.value} value={u.value}>{u.label}</option>)}
                </select>
                <input
                  type="number"
                  value={newItem.rate}
                  onChange={(e) => setNewItem({ ...newItem, rate: e.target.value })}
                  placeholder="Rate $"
                  className="w-full bg-white/[0.04] border border-white/[0.08] rounded-xl px-4 py-3 text-sm outline-none focus:border-amber-500/40 transition-colors"
                />
              </div>
              <div className="flex gap-2">
                <button onClick={() => setShowAddForm(false)} className="flex-1 py-2.5 rounded-xl border border-white/[0.1] text-xs font-medium text-[#888]">Cancel</button>
                <button
                  onClick={handleAddItem}
                  disabled={!newItem.description || !newItem.rate}
                  className="flex-1 py-2.5 rounded-xl bg-amber-500/20 text-amber-400 text-xs font-medium hover:bg-amber-500/30 transition-colors disabled:opacity-30"
                >
                  Add Item
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Line Items by Room */}
        {Array.from(groupedByRoom.entries()).map(([roomId, items]) => {
          const room = rooms.find((r) => r.id === roomId);
          return (
            <div key={roomId ?? 'general'} className="mb-4">
              <h3 className="text-xs font-medium text-amber-400 uppercase tracking-wider mb-2 px-1">
                {room ? room.name : 'General'}
              </h3>
              <div className="space-y-1">
                {items.map((item) => (
                  <div
                    key={item.id}
                    className="flex items-center gap-3 p-3 rounded-xl bg-white/[0.02] border border-white/[0.04] hover:border-white/[0.08] transition-colors"
                  >
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">{item.description}</p>
                      <div className="flex items-center gap-2 text-[10px] text-[#888]">
                        <span>{item.scope}</span>
                        <span>&middot;</span>
                        <span>{toNumber(item.quantity).toLocaleString()} {item.unit}</span>
                        <span>&middot;</span>
                        <span>{formatCurrency(item.rate)}/{item.unit}</span>
                      </div>
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-sm font-medium">{formatCurrency(item.subtotal)}</p>
                    </div>
                    <button
                      onClick={() => handleDelete(item.id)}
                      className="p-1.5 rounded-lg hover:bg-red-500/10 text-[#555] hover:text-red-400 transition-colors"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          );
        })}

        {/* Pricing Controls */}
        <div className="mt-6 rounded-2xl bg-white/[0.02] border border-white/[0.06] p-4">
          <h3 className="text-xs font-medium text-[#888] uppercase tracking-wider mb-3">Pricing Summary</h3>
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-sm text-[#888]">Subtotal</span>
              <span className="text-sm font-medium">{formatCurrency(subtotal)}</span>
            </div>
            <div className="flex items-center gap-3">
              <Percent className="w-4 h-4 text-[#555]" />
              <span className="text-sm text-[#888]">Tax Rate</span>
              <input
                type="number"
                value={taxRate}
                onChange={(e) => setTaxRate(Number(e.target.value))}
                className="w-20 bg-white/[0.04] border border-white/[0.08] rounded-lg px-3 py-2 text-sm outline-none focus:border-amber-500/40 transition-colors text-right"
              />
              <span className="text-sm">%</span>
              <span className="text-sm ml-auto">{formatCurrency(taxAmount)}</span>
            </div>
            <div className="flex items-center gap-3">
              <DollarSign className="w-4 h-4 text-[#555]" />
              <span className="text-sm text-[#888]">Discount</span>
              <input
                type="number"
                value={discount}
                onChange={(e) => setDiscount(Number(e.target.value))}
                className="w-28 bg-white/[0.04] border border-white/[0.08] rounded-lg px-3 py-2 text-sm outline-none focus:border-amber-500/40 transition-colors text-right"
              />
            </div>
            <div className="border-t border-white/[0.06] pt-3 flex items-center justify-between">
              <span className="text-base font-semibold">Total</span>
              <span className="text-xl font-bold text-amber-400">{formatCurrency(total)}</span>
            </div>
            <div className="flex items-center justify-between text-xs text-[#888]">
              <span>Deposit ({appConfig.defaultDepositPercent}%)</span>
              <span>{formatCurrency(depositAmount)}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom CTA */}
      <div className="fixed bottom-0 left-0 right-0 z-30 liquid-glass border-t border-white/[0.06]">
        <div className="max-w-3xl mx-auto px-4 py-3 flex gap-3">
          <button
            onClick={() => navigate(`/project/${pid}/rooms`)}
            className="flex-1 py-3 rounded-xl border border-white/[0.1] text-sm font-medium text-[#888] hover:bg-white/5 transition-colors"
          >
            Back
          </button>
          <button
            onClick={() => {
              handleUpdatePricing();
              navigate(`/project/${pid}/pdf`);
            }}
            className="flex-[2] py-3 rounded-xl bg-gradient-to-r from-amber-500 to-amber-600 text-white text-sm font-medium hover:from-amber-400 hover:to-amber-500 transition-all shadow-lg shadow-amber-500/20 flex items-center justify-center gap-2"
          >
            <FileText className="w-4 h-4" />
            Preview & Sign
          </button>
        </div>
      </div>
    </div>
  );
}
