import type { AppUser } from "./lib/supabase-db";
import type { LineItem, MediaAsset as Media, Project, Room } from "@/types";

const now = new Date();

export const mockUser: AppUser = {
  id: "dev-estimator",
  name: "Luna Estimator",
  email: "estimator@luna.local",
  avatar: null,
  role: "admin",
};

let nextProjectId = 2;
let nextRoomId = 4;
let nextLineItemId = 5;
let nextMediaId = 1;

export const mockProjects: Project[] = [
  {
    id: 1,
    userId: "dev-estimator",
    estimateNumber: "LUNA-DEMO-001",
    status: "draft",
    customerName: "Sarah Whitaker",
    customerPhone: "(843) 555-0184",
    customerEmail: "sarah@example.com",
    propertyAddress: "214 Magnolia Trace\nBluffton, SC 29910",
    propertyType: "Single Family",
    projectType: "Interior Painting",
    notes: "Client wants a clean modern palette and smoother ceiling finish in repaired areas.",
    internalNotes: "Upsell trim package and moisture-resistant bath paint.",
    leadSource: "Referral",
    tags: ["demo", "interior"],
    crmContactId: null,
    crmOpportunityId: null,
    crmEstimateId: null,
    crmSyncStatus: "not_needed",
    subtotal: "4865.00",
    taxRate: "0.00",
    taxAmount: "0.00",
    discountAmount: "0.00",
    total: "4865.00",
    depositPercent: 50,
    depositAmount: "2432.50",
    customerSignedAt: null,
    customerSignatureName: null,
    estimatorSignedAt: null,
    estimatorSignatureName: null,
    unsignedPdfUrl: null,
    signedPdfUrl: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockRooms: Room[] = [
  {
    id: 1,
    projectId: 1,
    name: "Living Room",
    sortOrder: 0,
    length: "18",
    width: "14",
    height: "9",
    wallSqFt: "576",
    ceilingSqFt: "252",
    totalSqFt: "828",
    doorCount: 2,
    windowCount: 3,
    trimLinearFt: "42",
    baseboardLinearFt: "42",
    hasDrywallRepair: ["cracks"],
    paintScope: ["walls", "ceiling", "trim"],
    textureScope: [],
    prepComplexity: "standard",
    repairComplexity: "minor",
    paintBrand: "Sherwin-Williams",
    paintColor: "Repose Gray",
    paintColorCode: "SW 7015",
    finishType: "Eggshell",
    productLine: "Duration Home",
    coats: 2,
    photos: [],
    aiVisualizationUrl: null,
    notes: "Hairline settling crack above fireplace.",
    internalNotes: null,
    subtotal: "2318.00",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    projectId: 1,
    name: "Kitchen",
    sortOrder: 1,
    length: "12",
    width: "10",
    height: "9",
    wallSqFt: "396",
    ceilingSqFt: "120",
    totalSqFt: "516",
    doorCount: 1,
    windowCount: 1,
    trimLinearFt: "26",
    baseboardLinearFt: "26",
    hasDrywallRepair: [],
    paintScope: ["walls", "ceiling"],
    textureScope: [],
    prepComplexity: "standard",
    repairComplexity: "none",
    paintBrand: "Sherwin-Williams",
    paintColor: "Alabaster",
    paintColorCode: "SW 7008",
    finishType: "Satin",
    productLine: "Emerald",
    coats: 2,
    photos: [],
    aiVisualizationUrl: null,
    notes: null,
    internalNotes: null,
    subtotal: "1205.00",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 3,
    projectId: 1,
    name: "Primary Bedroom",
    sortOrder: 2,
    length: "16",
    width: "14",
    height: "9",
    wallSqFt: "540",
    ceilingSqFt: "224",
    totalSqFt: "764",
    doorCount: 2,
    windowCount: 2,
    trimLinearFt: "38",
    baseboardLinearFt: "38",
    hasDrywallRepair: ["small_holes"],
    paintScope: ["walls", "ceiling", "doors"],
    textureScope: [],
    prepComplexity: "standard",
    repairComplexity: "minor",
    paintBrand: "Benjamin Moore",
    paintColor: "Sea Salt",
    paintColorCode: "SW 6204",
    finishType: "Eggshell",
    productLine: "Regal Select",
    coats: 2,
    photos: [],
    aiVisualizationUrl: null,
    notes: null,
    internalNotes: null,
    subtotal: "1342.00",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockLineItems: LineItem[] = [
  {
    id: 1,
    projectId: 1,
    roomId: 1,
    description: "Living Room - Wall Painting",
    category: null,
    scope: "Paint - Walls",
    quantity: "576",
    unit: "sqft",
    rate: "2.50",
    subtotal: "1440.00",
    sortOrder: 0,
    isInternal: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 2,
    projectId: 1,
    roomId: 1,
    description: "Living Room - Ceiling Painting",
    category: null,
    scope: "Paint - Ceiling",
    quantity: "252",
    unit: "sqft",
    rate: "2.00",
    subtotal: "504.00",
    sortOrder: 1,
    isInternal: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 3,
    projectId: 1,
    roomId: 2,
    description: "Kitchen - Wall & Ceiling Painting",
    category: null,
    scope: "Paint - Walls",
    quantity: "516",
    unit: "sqft",
    rate: "2.10",
    subtotal: "1083.60",
    sortOrder: 0,
    isInternal: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 4,
    projectId: 1,
    roomId: 3,
    description: "Primary Bedroom - Paint & Minor Drywall Prep",
    category: null,
    scope: "Prep Work",
    quantity: "764",
    unit: "sqft",
    rate: "2.41",
    subtotal: "1841.24",
    sortOrder: 0,
    isInternal: 0,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockMedia: Media[] = [];

export function makeEstimateNumber() {
  return `LUNA-DEMO-${String(nextProjectId).padStart(3, "0")}`;
}

export function nextIds() {
  return {
    projectId: nextProjectId++,
    roomId: nextRoomId++,
    lineItemId: nextLineItemId++,
    mediaId: nextMediaId++,
  };
}
